version: '3.2'
services:
  apache:
    container_name: 'apache'
    build: 
      context: ./docker/apache_docker/.
      dockerfile: Dockerfile # ネットワーク利用時
      #dockerfile: Dockerfile_local # ローカルで実験する際

      # build時に使う
      args:
        DOMAIN_NAME: ${DOMAIN_NAME} 
    ports : 
      - "443:443"
      - "80:80"
    volumes:
      - ./data/apache_log:/var/log/apache2 # apache2のlog保存用
      - /etc/letsencrypt:/etc/letsencrypt # letsencryptの証明書保存用
    # コンテナ実行時に使用
    environment:
      - 'TZ=Asia/Tokyo'
      - EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PASSPHRASE=${PASSPHRASE}
    
    restart: always
  streamlit:
    container_name: 'streamlit'
    build: 
      context: ./docker/streamlit_docker/.
      dockerfile: Dockerfile
    env_file:
      - .env
    # コンテナ実行時に使用
    environment:
      - 'TZ=Asia/Tokyo'
    ports:
      - "8501:8501"
      - "8502:8502"
    expose:
      - "8501"
    command: sh -c "streamlit run chat_openai0_28.py"
    volumes:
      - ./data/streamlit_log:/root/log/  # log保存用
      - ./docker/streamlit_docker:/root/docker/ # chat_openai0_28.pyアクセス用
    restart: always
    working_dir: '/root/docker/'
  

  redis:
    container_name: 'redis'
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./data/redis_snapshot/:/data/ # snapshot保存用
      - ./docker/redis_conf/:/usr/local/etc/redis/ # redis設定用
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

