version: '3.2'
services:
  apache:
    container_name: 'apache'
    build: 
      context: ./docker/apache_docker/.
      dockerfile: Dockerfile
      # build時に使う
      args:
        DOMAIN_NAME: ${DOMAIN_NAME} 
    ports : 
      - "443:443"
      - "80:80"
    volumes:
      - ./data/apache_log:/var/log/apache2 # apache2のlog保存用
      - /etc/letsencrypt:/etc/letsencrypt # letsencryptの証明書保存用
    # コンテナ実行時に使用
    environment:
      - 'TZ=Asia/Tokyo'
      - EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PASSPHRASE=${PASSPHRASE}
    
    restart: always
  streamlit:
    container_name: 'streamlit'
    build: 
      context: ./docker/streamlit_docker/.
      dockerfile: Dockerfile
    # コンテナ実行時に使用
    environment:
      - 'TZ=Asia/Tokyo'
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_TYPE=${OPENAI_API_TYPE}
      - API_BASE=${OPENAI_API_BASE}
      - API_VERSION=${OPENAI_API_VERSION}
      - LATE_LIMIT=${LATE_LIMIT}
      - AVAILABLE_MODELS=${AVAILABLE_MODELS}
      - TITLE_MODEL=${TITLE_MODEL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DOWNLOAD_DATA_WORD=${DOWNLOAD_DATA_WORD}
      - EXPIRE_TIME=${EXPIRE_TIME}
      - API_COST=${API_COST}
    #ports:
    #  - "8501:8501"
    #  - "8502:8502"
    expose:
      - "8501"
    command: sh -c "streamlit run chat_openai0_28.py"
    depends_on:
      - apache
      - redis_6379
    volumes:
      - ./data/streamlit_log:/root/log/  # log保存用
      - ./docker/streamlit_docker:/root/docker/ # chat_openai0_28.pyアクセス用
    restart: always
    working_dir: '/root/docker/'
  

  redis_6379:
    container_name: 'redis_6379'
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./data/redis_6379_snapshot/:/data/ # snapshot保存用
      - ./docker/redis_conf/6379/:/usr/local/etc/redis/ # redis設定用
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

